# Generated by Django 5.1.3 on 2024-12-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='child',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('children', models.ManyToManyField(related_name='activities', to='api.child')),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
